### PR TITLE
INTMDB-218: fixes the bug when you try to add more than 100 ip whitelist

### LINKED ISSUE #470: Adding IP to access List failed when lot of entries
Hi everyone, 

I use terraform with azure provider and mongodbatlas provider in order to add azure outbound IP in Atlas IP Access List.

> I don't use peering VPC and private link because some azure services are not in private VPC and some Atlas environement are in shared tier.

My terraform script work fine since many months but last days I needed to add more IP address (about 50). 
When terraform add IP to Atlas, some IP throwing an error after 21 retry. Howerver when I check in Atlas UI I see all IP has been added but terraform failed.

### Terraform CLI and Terraform MongoDB Atlas Provider Version
Terraform v0.15.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.9.1

### Terraform Configuration File 
No specific configuration

```hcl
# distinct_outbound_ips =>  List of 50 IP
#   ["yyy.50.2.xx",
#  "yyy.50.2.xx",
#  "yyy.61.224.xx"
#   ...]

output "outbound_ips" {
  value = local.distinct_outbound_ips
}

# Add Outbount Ip to Mongo Atlas
resource "mongodbatlas_project_ip_access_list" "applications_access_list" {
  for_each =  {
        for key, value in local.distinct_outbound_ips : key => value
  }
  project_id = var.mongodb_atlas.project_id
  ip_address = each.value
  comment    = format("Azure %s %s %s","azure", "prod", each.key)
}

```

> I also tried with `mongodbatlas_project_ip_whitelist` same result 

### Steps to Reproduce
1. Init
```
terraform init `
    -backend-config="subscription_id=$Env:ARM_SUBSCRIPTION_ID" `
    -backend-config="storage_account_name=$Env:ARM_STORAGE_ACCOUNT" `
    -backend-config="container_name=container-tfstate" `
    -backend-config="key=terraform" `
    -backend-config="tenant_id=$Env:ARM_TENANT_ID" `
    -backend-config="client_id=$Env:ARM_CLIENT_ID" `
    -backend-config="client_secret=$Env:ARM_CLIENT_SECRET" `
    -backend-config="resource_group_name=$Env:RESOURCE_GROUP"
```
2. `terraform workspace select prod`
3. `terraform apply -var-file="env/env.prod.tfvars"`

### Expected Behavior
All Ip address in list should be add to Atlas Access List with no error

### Actual Behavior
All IP has been added but terraform failed 

### Crash Output
```
mongodbatlas_project_ip_whitelist.applications_access_list["38"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["46"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["28"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["11"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["17"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["20"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["0"]: Creating...
mongodbatlas_project_ip_whitelist.applications_access_list["25"]: Creating...

.....

mongodbatlas_project_ip_whitelist.applications_access_list["0"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["38"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["11"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["46"]: Still creating... [3m20s elapsed]
mongodbatlas_project_ip_whitelist.applications_access_list["25"]: Still creating... [3m20s elapsed]

 Error: error creating Project IP Whitelist information: couldn't find resource (21 retries)

   with mongodbatlas_project_ip_whitelist.applications_access_list["17"],
   on main.tf line 781, in resource "mongodbatlas_project_ip_whitelist" "applications_access_list":
  781: resource "mongodbatlas_project_ip_whitelist" "applications_access_list" {

```
> But IPs were added

### PR DESCRIPTION
**Pull request by coderGo93**
## Description

Fixes the bug where it fails after trying to add 100 or more ip whitelists

Link to any related issue(s):

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the Terraform contribution guidelines
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code

### CODE REVIEW

File: mongodbatlas/resource_mongodbatlas_project_ip_access_list.go [hunk 1]
```diff
@@ -127,17 +127,21 @@ func resourceMongoDBAtlasProjectIPAccessListCreate(ctx context.Context, d *schem
...
 			}
 
-			if accessList.TotalCount > 0 {
-				accessListEntry := ipAddress
-				if cidrBlock != "" {
-					accessListEntry = cidrBlock
-				}
+			accessListEntry := ipAddress
+			if cidrBlock != "" {
+				accessListEntry = cidrBlock
```
Comment (thetonymaster) [inline mongodbatlas/resource_mongodbatlas_project_ip_access_list.go:132]: Nitpick: `if len(cidrBlock) > 0`

**Review by thetonymaster — APPROVED** [review]

File: mongodbatlas/resource_mongodbatlas_project_ip_access_list.go [hunk 2]
```diff
@@ -127,17 +127,21 @@ func resourceMongoDBAtlasProjectIPAccessListCreate(ctx context.Context, d *schem
...
+			accessListEntry := ipAddress
+			if len(cidrBlock) > 0 {
+				accessListEntry = cidrBlock
+			}
 
-				for _, entry := range accessList.Results {
-					if entry.IPAddress == accessListEntry || entry.CIDRBlock == accessListEntry {
-						return accessList, "created", nil
-					}
+			exists, err := isProjectIPAccessInTheList(ctx, conn, projectID, accessListEntry)
```
Comment (andreaangiolillo) [inline mongodbatlas/resource_mongodbatlas_project_ip_access_list.go]: [nit] this name `isProjectIPAccessInTheList` does not help. Maybe something better would be `isEntryInProjectAccessList`

File: mongodbatlas/resource_mongodbatlas_project_ip_access_list.go [hunk 3]
```diff
@@ -278,3 +283,54 @@ func resourceMongoDBAtlasIPAccessListImportState(ctx context.Context, d *schema.
...
+
+		if accessList.TotalCount > 0 {
+			for _, result := range accessList.Results {
+				if result.IPAddress == entry || result.CIDRBlock == entry {
+					exists = true
+					break
+				}
+			}
+		}
+
```
Comment (andreaangiolillo) [inline mongodbatlas/resource_mongodbatlas_project_ip_access_list.go:311]: [nit] I think that this may be more readable 

```golang
		if exists {
			return nil
		}

	
		currentPage, err = resp.CurrentPage()
		if err != nil {
			return resource.NonRetryableError(fmt.Errorf(errorAccessListRead, err))
		}

		if !resp.IsLastPage() {
			currentPage++
			return resource.RetryableError(fmt.Errorf("[DEBUG] Current page : %d Next page: %d, will retry again", currentPage-1, currentPage))
		}
		
		return nil
```

File: mongodbatlas/resource_mongodbatlas_project_ip_access_list.go [hunk 4]
```diff
@@ -278,3 +283,54 @@ func resourceMongoDBAtlasIPAccessListImportState(ctx context.Context, d *schema.
 
 	return []*schema.ResourceData{d}, nil
 }
+
+func isProjectIPAccessInTheList(ctx context.Context, conn *matlas.Client, projectID, entry string) (bool, error) {
```
Comment (andreaangiolillo) [inline mongodbatlas/resource_mongodbatlas_project_ip_access_list.go]: [q] Could you show me where the bug was? I see that the main difference in your solution is that now we have `isProjectIPAccessInTheList` to check that the entry is in the project access list. Thanks!

**Review by andreaangiolillo — COMMENTED** [review]
Thanks for fixing this! I have only one question as I am struggling to see where was the piece of code that was preventing adding more than 100 ips.

File: mongodbatlas/resource_mongodbatlas_project_ip_access_list.go (hunk 2 above)
Comment (coderGo93) [reply mongodbatlas/resource_mongodbatlas_project_ip_access_list.go]: Sure,will do that, thank you

File: mongodbatlas/resource_mongodbatlas_project_ip_access_list.go (hunk 4 above)
Comment (coderGo93) [reply mongodbatlas/resource_mongodbatlas_project_ip_access_list.go]: The bug was is that when you create 100 ips or more, it will fail with an error of 21 retries or something like that, I realized that happens because when you make a list, it returns maximum 100 items(if not specified in list options) but when you read TotalCount is more than 100, if the entry has not been found it's probably is in after 100 item, so it would never be found hence the error of 21 retries, so I made a function and use the List options so it if the first page the entry has not been found yet, will retry again with another page until is found(or if is last page)

Comment (andreaangiolillo) [reply mongodbatlas/resource_mongodbatlas_project_ip_access_list.go]: Thanks!

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by themantissa — APPROVED** [review]
LGTM!
