### PR TITLE
fix: Sets all attributes of Azure `mongodbatlas_network_peering` as ForceNew, forcing recreation of the resource when updating 

### LINKED ISSUE #2281: [Bug]: error updating MongoDB Network Peering Connection - 400 (request "INVALID_ATTRIBUTE") Invalid attribute azureDirectoryId specified
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.16.0

### Terraform Version

v1.8.3

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

When attempting to create a networking peering with Azure using Terraform I get the error:

│ Error: error updating MongoDB Network Peering Connection (<>): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/<>/peers/<>: 400 (request "INVALID_ATTRIBUTE") Invalid attribute azureDirectoryId specified.

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_network_peering" "peering" {
  project_id    = local.project_id
  container_id  = mongodbatlas_network_container.container.container_id
  provider_name = "AZURE"
  azure_directory_id    = local.azure_directory_id
  azure_subscription_id = local.azure_subscription_id
  resource_group_name   = local.azure_resources_group_name
  vnet_name             = local.azure_vnet_name
  depends_on            = [mongodbatlas_network_container.container]
}
```

### Steps To Reproduce

Using Terraform v1.8.3, mongodbatlas provider version v1.16.0 apply the above configuration

### Logs

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oarbusi**
## Description

Sets all attributes when updating an Azure network peering resource. 
Fixes https://github.com/mongodb/terraform-provider-mongodbatlas/issues/2281

Link to any related issue(s): CLOUDP-249269

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR. A migration guide must be created or updated if the new feature will go in a major version.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR. A migration guide must be created or updated.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contributing guides](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/contributing/README.md)
- [x] I have checked that this change does not generate any credentials and that **they are NOT accidentally logged anywhere**.
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code
- [x] If changes include deprecations or removals, I defined an isolated PR with a relevant title as it will be used in the auto-generated changelog.
- [x] If changes include removal or addition of 3rd party GitHub actions, I updated our internal document. Reach out to the APIx Integration slack channel to get access to the internal document.

### CODE REVIEW

**Review by kanchana-mongodb — APPROVED** [review]

File: internal/service/networkpeering/resource_network_peering_test.go [hunk 1]
```diff
@@ -64,6 +64,50 @@ func TestAccNetworkRSNetworkPeering_basicAzure(t *testing.T) {
 	})
 }
 
+func TestAccNetworkRSNetworkPeering_updateBasicAzure(t *testing.T) {
+	acc.SkipTestForCI(t) // needs Azure configuration
```
Comment (marcosuma) [inline internal/service/networkpeering/resource_network_peering_test.go]: :( is it hard to have this information in our CI setup so that we can actually have it running?

File: .changelog/2299.txt [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
+resource/mongodbatlas_network_peering: sets all necessary attributes for update of Azure network peering
```
Comment (AgustinBettati) [inline .changelog/2299.txt]:
```suggestion
resource/mongodbatlas_network_peering: Sets all necessary attributes for update of Azure network peering
```

File: internal/service/networkpeering/resource_network_peering.go [hunk 3]
```diff
@@ -103,21 +103,25 @@ func Resource() *schema.Resource {
...
 				Type:     schema.TypeString,
 				Optional: true,
 				Computed: true,
+				ForceNew: true,
 			},
 			"vnet_name": {
 				Type:     schema.TypeString,
 				Optional: true,
 				Computed: true,
+				ForceNew: true,
```
Comment (AgustinBettati) [inline internal/service/networkpeering/resource_network_peering.go:124]: I am not clear why we are marking as `ForceNew` (applies to above attributes as well). My understanding is that after adjusting the PATCH request this property can be updated successfully. Defining `ForceNew` forces terraform to avoid calling the update and instead call delete -> create.

File: internal/service/networkpeering/resource_network_peering_test.go (hunk 1 above)
Comment (oarbusi) [reply internal/service/networkpeering/resource_network_peering_test.go]: Main issue I found while running them locally is the limitation of network_container that in AWS and Azure there can only be one container per cloud provider region and that you can't delete a network peering container if your project contains clusters. I'll work around that so that we can have the tests run in the CI

File: internal/service/networkpeering/resource_network_peering.go (hunk 3 above)
Comment (oarbusi) [reply internal/service/networkpeering/resource_network_peering.go:124]: When a network peering connection has been created and the status is ACTIVE, the network peering connection can not be modified and instead needs to be deleted and recreated. A network peering connection can only be updated if the creation has failed and the status is FAILED.

File: internal/service/networkpeering/resource_network_peering_test.go (hunk 1 above)
Comment (lantoli) [reply internal/service/networkpeering/resource_network_peering_test.go]: in case it can help, we improved cleanup process to delete endpoints: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/scripts/cleanup-test-env.sh#L19
we could improve it to delete these projects as well if needed

File: internal/service/networkpeering/resource_network_peering_test.go [hunk 4]
```diff
@@ -275,7 +319,7 @@ func configAzure(projectID, providerName, directoryID, subscriptionID, resourceG
 			azure_directory_id    = "%[3]s"
 			azure_subscription_id = "%[4]s"
 			resource_group_name   = "%[5]s"
-			vnet_name	            = "%[6]s"
+			vnet_name	          = "%[6]s"
```
Comment (lantoli) [inline internal/service/networkpeering/resource_network_peering_test.go]: better %[6]q than "%[6]s", same for others

**Review by lantoli — APPROVED** [review]

File: internal/service/networkpeering/resource_network_peering_test.go (hunk 4 above)
Comment (oarbusi) [reply internal/service/networkpeering/resource_network_peering_test.go]: done!

File: internal/service/networkpeering/resource_network_peering_test.go (hunk 1 above)
Comment (oarbusi) [reply internal/service/networkpeering/resource_network_peering_test.go]: Done! Now the tests run in the CI

**Comment by oarbusi** [comment]
After adding `ForceNew` to the Azure attributes, Azure update does not have to be handled in the Update method. Will investigate if AWS and GCP have the same behaviour and create a follow up PR if needed

File: internal/service/networkpeering/resource_network_peering_test.go (hunk 1 above)
Comment (marcosuma) [reply internal/service/networkpeering/resource_network_peering_test.go]: Thank you very much!

File: internal/service/networkpeering/resource_network_peering.go (hunk 3 above)
Comment (AgustinBettati) [reply internal/service/networkpeering/resource_network_peering.go:124]: thanks for clarifying! Would update the changelog entry to clarify that azure properties will force a delete and create.

**Review by AgustinBettati — APPROVED** [review]
LGTM
