### PR TITLE
fix: Changes `user_id` and `username` to be Optional and Computed in `mongodbatlas_cloud_user_org_assignment` data source

### LINKED ISSUE #3831: [Bug]: Error in resource mongodbatlas_cloud_user_team_assignment when updating resource mongodbatlas_organization
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Provider Version

v2.1.0

### Terraform Version

v1.13.4

### Terraform Edition

Terraform Cloud

### Current Behavior

When updating a mongodbatlas_organization resource (add security contact), the existing mongodbatlas_cloud_user_team_assignment resources error because the user_id is undefined

```
Error: Missing Configuration for Required Attribute
│ 
│   with mongodbatlas_cloud_user_team_assignment.platform_admin_foo,
│   on user-team-assignments.tf line 22, in resource "mongodbatlas_cloud_user_team_assignment" "platform_admin_foo":
│   22:   user_id = data.mongodbatlas_cloud_user_org_assignment.foo.user_id
│ 
│ Must set a configuration value for the user_id attribute as the provider
│ has marked it as required.
```

### Terraform configuration to reproduce the issue

```hcl
resource "mongodbatlas_organization" "org" {
  name = "Org Name"
}

data "mongodbatlas_cloud_user_org_assignment" "foo" {
  org_id   = mongodbatlas_organization.org.org_id
  username = "foo@example.com"
}

resource "mongodbatlas_team" "platform_admin" {
  org_id = mongodbatlas_organization.org.org_id
  name   = "platform-admin"
}

resource "mongodbatlas_cloud_user_team_assignment" "platform_admin_foo" {
  org_id  = mongodbatlas_organization.org.org_id
  team_id = mongodbatlas_team.platform_admin.team_id
  user_id = data.mongodbatlas_cloud_user_org_assignment.foo.user_id
}
```

### Steps To Reproduce

Once you have applied the change above, add the security contact to the org resource and run a plan.  This will result in the following error `Error: Missing Configuration for Required Attribute`

### Logs

```txt

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oarbusi**
## Description

Changes `user_id` and `username` to be Optional and Computed in `mongodbatlas_cloud_user_org_assignment` data source. Fixes https://github.com/mongodb/terraform-provider-mongodbatlas/issues/3831

Link to any related issue(s): CLOUDP-356519

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR. A migration guide must be created or updated if the new feature will go in a major version.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR. A migration guide must be created or updated.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have read the [contributing guides](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/contributing/README.md)
- [ ] I have checked that this change does not generate any credentials and that **they are NOT accidentally logged anywhere**.
- [ ] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run make fmt and formatted my code
- [ ] If changes include deprecations or removals I have added appropriate changelog entries.
- [ ] If changes include removal or addition of 3rd party GitHub actions, I updated our internal document. Reach out to the APIx Integration slack channel to get access to the internal document.

### CODE REVIEW

File: internal/service/clouduserorgassignment/schema.go [hunk 1]
```diff
@@ -154,11 +156,19 @@ func dataSourceOverridenFields() map[string]dsschema.Attribute {
...
+			Validators: []validator.String{
+				stringvalidator.ExactlyOneOf(path.MatchRoot("username")),
+			},
 		},
 		"username": dsschema.StringAttribute{
 			Optional:            true,
+			Computed:            true,
 			MarkdownDescription: "Email address that represents the username of the MongoDB Cloud user.",
+			Validators: []validator.String{
+				stringvalidator.ExactlyOneOf(path.MatchRoot("user_id")),
```
Comment (EspenAlbert) [inline internal/service/clouduserorgassignment/schema.go:170]: Can we update our acceptance tests to see if the user_id/username gets populated?

File: internal/service/clouduserorgassignment/resource_test.go [hunk 2]
```diff
@@ -118,23 +118,43 @@ func testAccCloudUserOrgAssignmentWithDataSourceConfig(orgID, username string, r
...
 }
-`, orgID, username, rolesStr, orgID, orgID)
+
+# The following resources verify that user_id is properly marked as Computed
+# When querying by username, user_id must be marked as "Computed: true" in the schema
+# so that Terraform knows its value will be available for use in other resources.
+# Without "Computed: true", Terraform will fail at plan time because it cannot validate
+# that user_id will be available as an input to the team assignment resource below, where user_id is required.
+#   - Without Computed: This test FAILS at plan time
+#   - With Computed: This test SUCCEEDS
```
Comment (AgustinBettati) [inline internal/service/clouduserorgassignment/resource_test.go:146]: q: Cant we adjust `cloudUserOrgAssignmentChecks` to ensure both `username` and `user_id` are populated in both data source definitions?

**Review by AgustinBettati — APPROVED** [review]
LGTM

File: internal/service/clouduserorgassignment/resource_test.go (hunk 2 above)
Comment (oarbusi) [reply internal/service/clouduserorgassignment/resource_test.go:146]: this was already being tested and the attributes were being populated. The issue described in the GH issue that we are fixing here appears when those attributes are used as inputs in Required fields of other resources/data sources, that is why I modified how I did the test

File: internal/service/clouduserorgassignment/schema.go (hunk 1 above)
Comment (oarbusi) [reply internal/service/clouduserorgassignment/schema.go:170]: Replied to the same question in other [thread](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/3911#discussion_r2549282254). TLDR: user_id/username was already being populated and was checked in the test. See changes in internal/service/clouduserorgassignment/resource_test.go for more details on how I test this fix

File: internal/service/clouduserorgassignment/resource_test.go (hunk 2 above)
Comment (EspenAlbert) [reply internal/service/clouduserorgassignment/resource_test.go:146]: nice!

File: internal/service/clouduserorgassignment/schema.go (hunk 1 above)
Comment (EspenAlbert) [reply internal/service/clouduserorgassignment/schema.go:170]: Ty!

**Review by EspenAlbert — APPROVED** [review]
Nice finding. Do we want to include that `why` in the changelog maybe?

**Review by lantoli — APPROVED** [review]
nice!

File: internal/service/clouduserorgassignment/resource_test.go [hunk 3]
```diff
@@ -118,23 +118,43 @@ func testAccCloudUserOrgAssignmentWithDataSourceConfig(orgID, username string, r
...
 data "mongodbatlas_cloud_user_org_assignment" "by_user_id" {
-  org_id   = "%s"
+  org_id   = %[1]q
   user_id  = mongodbatlas_cloud_user_org_assignment.test.user_id
 }
-`, orgID, username, rolesStr, orgID, orgID)
+
+# The following resources verify that user_id is properly marked as Computed
+# When querying by username, user_id must be marked as "Computed: true" in the schema
+# so that Terraform knows its value will be available for use in other resources.
```
Comment (jromo-mdb) [inline internal/service/clouduserorgassignment/resource_test.go:142]:
```suggestion
# so that Terraform can recognize its value will be available for use in other resources.
```

**Review by jromo-mdb — APPROVED** [review]
Approved with Minor style guide comment https://www.mongodb.com/docs/meta/style-guide/writing/use-effective-verbs/#don-t-humanize-inanimate-objects
