### PR TITLE
fix: remove collectionName from user role doesn't work

### LINKED ISSUE #1462: Changing DB user role from readwrite@DB.Col1 to readwrite@DB doesn't work
Hi,

we have a problem changing role of a db user from collection based to DB(All Collections) based.

Versions:
```hcl
  mongodbatlas 1.11.1
  terraform: 1.5.0
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. Create a db user with (apply):
```
 roles {
    role_name     = "readWrite"
    database_name = "Inventory"
    collection_name = "Inventory"
  }
 roles {
    role_name     = "readWrite"
    database_name = "Inventory"
    collection_name = "Inventory2"
  }
```

2.  Change it to (apply):
```
 roles {
    role_name     = "readWrite"
    database_name = "Inventory"
  }
```

### Expected Behavior

User in db has readWrite@Inventory

### Actual Behavior

User in db has readWrite@Inventory.Inventory or readWrite@Inventory.Inventory2

### PR DESCRIPTION
**Pull request by marcosuma**
## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s): https://jira.mongodb.org/browse/INTMDB-1062
Closes #1462

All details and investigation is written in the related issue.

## Type of change:

- [X] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [X] I have read the [contribution guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md)
- [X] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [X] I have added any necessary documentation (if appropriate)
- [X] I have run make fmt and formatted my code

### CODE REVIEW

**Review by gssbzn — APPROVED** [review]

File: mongodbatlas/fw_resource_mongodbatlas_database_user.go [hunk 1]
```diff
@@ -165,6 +165,7 @@ func (r *DatabaseUserRS) Schema(ctx context.Context, req resource.SchemaRequest,
 					Attributes: map[string]schema.Attribute{
 						"collection_name": schema.StringAttribute{
 							Optional: true,
+							Default:  stringdefault.StaticString(""),
```
Comment (andreaangiolillo) [inline mongodbatlas/fw_resource_mongodbatlas_database_user.go]: What do we send to the endpoint when the user does not provide collection_name?

Comment (andreaangiolillo) [reply mongodbatlas/fw_resource_mongodbatlas_database_user.go]: I see that the param is not required in the API [endpoint](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Database-Users/operation/createDatabaseUser) so I have a couple of thoughts:

- the collection_name should not be compute
I tested this quickly and the endpoint does not return collection_name when it is not provided in the request
```
{
  "awsIAMType": "NONE",
  "databaseName": "admin",
  "groupId": "63f4d4a47baeac59406dc131",
  "ldapAuthType": "NONE",
  "links": [
    {
      "href": "https://cloud-dev.mongodb.com/api/atlas/v2/groups/63f4d4a47baeac59406dc131/databaseUsers/admin/myUser",
      "rel": "self"
    }
  ],
  "oidcAuthType": "NONE",
  "roles": [
    {
      "databaseName": "admin",
      "roleName": "clusterMonitor"
    },
    {
      "databaseName": "admin",
      "roleName": "backup"
    }
  ],
  "username": "myUser",
  "x509Type": "NONE"
}
```

- We should not set default here because collection_name is not required
- The bug may be in [newMongoDBAtlasRoles](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/0694a78eaeb73783ea2a115917dda88f17549e35/mongodbatlas/fw_resource_mongodbatlas_database_user.go#L477)
```golang
	for i, v := range roles {
		out[i] = matlas.Role{
			RoleName:       v.RoleName.ValueString(),
			DatabaseName:   v.DatabaseName.ValueString(),
			CollectionName: v.CollectionName.ValueString(),
		}
	}
```
Here we are adding collection_name all the time where we may need instead to check for null.

Comment (marcosuma) [reply mongodbatlas/fw_resource_mongodbatlas_database_user.go]: spoke offline and made changes to my initial proposal.

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by AgustinBettati — APPROVED** [review]

**Review by andreaangiolillo — APPROVED** [review]
