### PR TITLE
fix: Increases update wait time in `mongodbatlas_private_endpoint_regional_mode`

### LINKED ISSUE #3315: [Bug]: resource_private_endpoint_regional_mode does not delay long enough for state change to start
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Provider Version

v1.34.0

### Terraform Version

v1.5

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

We are attempting to flip the regional mode flag on projects, load cluster data sources and propagate new regional connection string information as updates elsewhere.

We notice the expected config updates are not happening during the initial terraform run, but subsequent runs result in the expected updates.

It looks like the 3 second delay [here](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/internal/service/privateendpointregionalmode/resource_private_endpoint_regional_mode.go#L120) before waiting on state changes is not sufficient. This results in the resource creation completing immediately after waiting 3s, before the cluster updates even begin.

### Terraform configuration to reproduce the issue

```hcl
terraform {
  backend "local" {}

  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "1.34.0"
    }
  }
}

locals {
  project_id   = "XXX"
  cluster_name = "XXX"

  regional_mode_enabled = false
}

resource "mongodbatlas_private_endpoint_regional_mode" "regional_mode" {
  project_id = local.project_id
  enabled    = local.regional_mode_enabled
}


data "mongodbatlas_advanced_cluster" "space" {
  project_id = local.project_id
  name       = local.cluster_name
  depends_on = [mongodbatlas_private_endpoint_regional_mode.regional_mode]
}

output "connection_strings" {
  value = data.mongodbatlas_advanced_cluster.space.connection_strings[0].private_endpoint
}
```

### Steps To Reproduce

1. apply terraform on a cluster/project without regional endpoints enabled
2. output shows a single private endpoint connection in non-regional mode:

```
connection_strings = tolist([
  {
    "connection_string" = "mongodb://pl-0-us-east-1.XXX.mongodb.net:1024,pl-0-us-east-1.XXX.mongodb.net:1025,pl-0-us-east-2.XXX.mongodb.net:1026,pl-0-us-east-2.XXX.mongodb.net:1027,pl-0-us-west-2.XXX.mongodb.net:1028/?ssl=true&authSource=admin"
    "endpoints" = tolist([
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_EAST_1"
      },
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_EAST_2"
      },
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_WEST_2"
      },
    ])
    "srv_connection_string" = "mongodb+srv://default-pl-0.XXX.mongodb.net"
    "srv_shard_optimized_connection_string" = ""
    "type" = "MONGOS"
  },
])
```
3. flip `regional_mode_enabled` local in configuration again and apply. expectation is that regional mode is enabled. expectation is that we get new connection strings, but connection strings are still non-regional:

```
  # mongodbatlas_private_endpoint_regional_mode.regional_mode will be updated in-place
  ~ resource "mongodbatlas_private_endpoint_regional_mode" "regional_mode" {
      ~ enabled    = false -> true
        id         = "XXX"
        # (1 unchanged attribute hidden)
    }
  ~ connection_strings = -> (known after apply
```

However, the output remains the same:

```
connection_strings = tolist([
  {
    "connection_string" = "mongodb://pl-0-us-east-1.XXX.mongodb.net:1024,pl-0-us-east-1.XXX.mongodb.net:1025,pl-0-us-east-2.XXX.mongodb.net:1026,pl-0-us-east-2.XXX.mongodb.net:1027,pl-0-us-west-2.XXX.mongodb.net:1028/?ssl=true&authSource=admin"
    "endpoints" = tolist([
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_EAST_1"
      },
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_EAST_2"
      },
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_WEST_2"
      },
    ])
    "srv_connection_string" = "mongodb+srv://default-pl-0.XXX.mongodb.net"
    "srv_shard_optimized_connection_string" = ""
    "type" = "MONGOS"
  },
])
```
4. re-apply terraform after some time. No detected changes required but connection strings are output correctly from the cluster data source

```
connection_strings = tolist([
  {
    "connection_string" = "mongodb://pl-0-us-east-1.XXX.mongodb.net:1024,pl-0-us-east-1.XXX.mongodb.net:1025/?ssl=true&authSource=admin"
    "endpoints" = tolist([
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_EAST_1"
      },
    ])
    "srv_connection_string" = "mongodb+srv://default-pl-0-us-east-1.XXX.mongodb.net"
    "srv_shard_optimized_connection_string" = "mongodb+srv://default-pl-0-us-east-1-lb.XXX.mongodb.net"
    "type" = "MONGOS"
  },
  {
    "connection_string" = "mongodb://pl-0-us-east-2.XXX.mongodb.net:1026,pl-0-us-east-2.XXX.mongodb.net:1027/?ssl=true&authSource=admin"
    "endpoints" = tolist([
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_EAST_2"
      },
    ])
    "srv_connection_string" = "mongodb+srv://default-pl-0-us-east-2.XXX.mongodb.net"
    "srv_shard_optimized_connection_string" = "mongodb+srv://default-pl-0-us-east-2-lb.XXX.mongodb.net"
    "type" = "MONGOS"
  },
  {
    "connection_string" = "mongodb://pl-0-us-west-2.XXX.mongodb.net:1028/?ssl=true&authSource=admin"
    "endpoints" = tolist([
      {
        "endpoint_id" = "vpce-XXX"
        "provider_name" = "AWS"
        "region" = "US_WEST_2"
      },
    ])
    "srv_connection_string" = "mongodb+srv://default-pl-0-us-west-2.XXX.mongodb.net"
    "srv_shard_optimized_connection_string" = "mongodb+srv://default-pl-0-us-west-2-lb.XXX.mongodb.net"
    "type" = "MONGOS"
  },
])
```

### Logs

```txt
From TF trace logs, we see the the `PATCH` operation to enable regionalMode and the subsequent query of clusters after 3s, at which point the cluster state is IDLE and the resource completes creation.

2025-05-05T11:37:40.682-0700 [DEBUG] provider.terraform-provider-mongodbatlas_v1.34.0: PATCH /api/atlas/v2/groups/XXX/privateEndpoint/regionalMode HTTP/1

2025-05-05T11:37:44.128-0700 [DEBUG] provider.terraform-provider-mongodbatlas_v1.34.0: GET /api/atlas/v2/groups/XXX/clusters?includeCount=true&includeDeletedWithRetainedBackups=false&itemsPerPage=100&pageNum=1 HTTP/1.1
...
2025-05-05T11:37:44.421-0700 [DEBUG] provider.terraform-provider-mongodbatlas_v1.34.0:    "stateName": "IDLE",

Meanwhile, polling the cluster separately shows the first state change does not happen until later:

Mon May  5 11:37:48 PDT 2025: stateName=IDLE
Mon May  5 11:37:49 PDT 2025: stateName=UPDATING
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lantoli**
## Description

Increases update wait time in `mongodbatlas_private_endpoint_regional_mode` so cluster connection strings are updated.

It fixes: https://github.com/mongodb/terraform-provider-mongodbatlas/issues/3315
It is based on: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/3316

Link to any related issue(s): CLOUDP-317448

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue). Please, add the "bug" label to the PR.
- [ ] New feature (non-breaking change which adds functionality). Please, add the "enhancement" label to the PR. A migration guide must be created or updated if the new feature will go in a major version.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). Please, add the "breaking change" label to the PR. A migration guide must be created or updated.
- [ ] This change requires a documentation update
- [ ] Documentation fix/enhancement

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have read the [contributing guides](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/contributing/README.md)
- [x] I have checked that this change does not generate any credentials and that **they are NOT accidentally logged anywhere**.
- [x] I have added tests that prove my fix is effective or that my feature works per HashiCorp requirements
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run make fmt and formatted my code
- [x] If changes include deprecations or removals I have added appropriate changelog entries.
- [x] If changes include removal or addition of 3rd party GitHub actions, I updated our internal document. Reach out to the APIx Integration slack channel to get access to the internal document.

### CODE REVIEW

**Review by oarbusi — APPROVED** [review]
LGTM

File: internal/service/privateendpointregionalmode/resource_private_endpoint_regional_mode.go [hunk 1]
```diff
@@ -116,8 +116,8 @@ func resourceUpdate(ctx context.Context, d *schema.ResourceData, meta any) diag.
 		Target:     []string{"IDLE", "DELETED"},
 		Refresh:    advancedcluster.ResourceClusterListAdvancedRefreshFunc(ctx, projectID, conn.ClustersApi),
 		Timeout:    d.Timeout(timeoutKey.(string)),
-		MinTimeout: 5 * time.Second,
-		Delay:      3 * time.Second,
+		MinTimeout: 15 * time.Second,
+		Delay:      30 * time.Second, // give time for cluster connection strings to be updated
```
Comment (AgustinBettati) [inline internal/service/privateendpointregionalmode/resource_private_endpoint_regional_mode.go:120]: nit: We usually cherry-pick at least one commit from the [original PR](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/3316) so the user contribution is preserved

**Review by AgustinBettati — APPROVED** [review]
LGTM

File: internal/service/privateendpointregionalmode/resource_private_endpoint_regional_mode.go (hunk 1 above)
Comment (lantoli) [reply internal/service/privateendpointregionalmode/resource_private_endpoint_regional_mode.go:120]: I know, but as in this [comment](https://github.com/mongodb/terraform-provider-mongodbatlas/issues/3315#issuecomment-2861828376),  the commit is by a different user that created the PR and the issue, that we haven't interacted with.

**Review by lmkerbey-mdb — APPROVED** [review]

**Review by maastha — APPROVED** [review]
